# -*- coding: utf-8 -*-
"""precompute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VdDc5LReut6rhZ2GWXp1WY5E3gyKn3IQ
"""

import os

CANDIDATES  = os.environ.get('CANDIDATES_PATH', './candidates.jsonl')
PRECOMPUTED = os.environ.get('PRECOMPUTED_DIR', './precomputed')

os.makedirs(PRECOMPUTED, exist_ok=True)
import json

candidates = []
with open(CANDIDATES, 'r') as f:
    for line in f:
        if line.strip():
            candidates.append(json.loads(line))

print(f'Loaded {len(candidates)} candidates')
import json
from datetime import datetime

TODAY = datetime(2026, 6, 28)

# --- City tier mapping ---
TIER_1_CITIES = {
    'mumbai', 'delhi', 'bangalore', 'bengaluru', 'hyderabad',
    'pune', 'noida', 'gurugram', 'gurgaon', 'chennai',
    'kolkata', 'ahmedabad', 'delhi ncr', 'ncr'
}

PREFERRED_CITIES = {'pune', 'noida'}  # JD preferred

def get_location_tier(location_str):
    """
    Returns:
        'preferred'  — Pune or Noida (JD preferred)
        'tier_1'     — Other Tier-1 Indian cities
        'other'      — Everything else
    """
    if not location_str:
        return 'other'
    loc = location_str.lower()
    for city in PREFERRED_CITIES:
        if city in loc:
            return 'preferred'
    for city in TIER_1_CITIES:
        if city in loc:
            return 'tier_1'
    return 'other'

def compute_yoe(career):
    total = 0
    for job in career:
        try:
            s = datetime.strptime(job['start_date'], '%Y-%m-%d')
            e = TODAY if not job.get('end_date') else datetime.strptime(job['end_date'], '%Y-%m-%d')
            total += max(0, (e.year - s.year) * 12 + e.month - s.month)
        except:
            pass
    return round(total / 12, 1)

def get_skill_durations(skills):
    """
    Returns dict of {skill_name_lower: duration_months}
    If duration_months missing, defaults to -1 (unknown)
    -1 = not provided, 0 = listed but never used (keyword stuffer signal)
    """
    result = {}
    for s in skills:
        name = s.get('name', '').lower().strip()
        if name:
            duration = s.get('duration_months', -1)
            if duration is None:
                duration = -1
            result[name] = int(duration)
    return result

feature_cache = {}

for cand in candidates:
    cid     = cand['candidate_id']
    profile = cand.get('profile', {})
    signals = cand.get('redrob_signals', {})
    career  = cand.get('career_history') or []
    skills  = cand.get('skills') or []

    yoe         = compute_yoe(career)
    skill_names = [s.get('name', '').lower() for s in skills]

    # Top 2 roles by duration for description (fixes truncation gap)
    career_sorted = sorted(
        career,
        key=lambda x: x.get('duration_months', 0),
        reverse=True
    )[:2]
    all_desc = ' '.join(
        j.get('description', '')[:400] for j in career_sorted
    ).lower()

    last_active = signals.get('last_active_date', '2020-01-01')
    try:
        inactive_days = (TODAY - datetime.strptime(last_active, '%Y-%m-%d')).days
    except:
        inactive_days = 999

    # Check if entire career is at consulting firms only
    consulting_firms = {
        'tcs', 'infosys', 'wipro', 'accenture', 'cognizant',
        'capgemini', 'hcl', 'tech mahindra', 'mphasis'
    }
    career_companies = [
        j.get('company', '').lower() for j in career
    ]
    is_consulting_only = (
        len(career_companies) > 0 and
        all(
            any(firm in company for firm in consulting_firms)
            for company in career_companies
        )
    )

    feature_cache[cid] = {
        # --- Experience ---
        'yoe'               : yoe,

        # --- Activity signals ---
        'inactive_days'     : inactive_days,
        'resp_rate'         : float(signals.get('recruiter_response_rate', 0) or 0),
        'notice_days'       : int(signals.get('notice_period_days', 90) or 90),
        'otw'               : bool(signals.get('open_to_work_flag', False)),
        'apps_30d'          : int(signals.get('applications_submitted_30d', 0) or 0),
        'saved_30d'         : int(signals.get('saved_by_recruiters_30d', 0) or 0),
        'resp_time_h'       : float(signals.get('avg_response_time_hours', 999) or 999),
        'github_score'      : float(signals.get('github_activity_score', -1) or -1),
        'interview_rate'    : float(signals.get('interview_completion_rate', 0) or 0),
        'profile_complete'  : float(signals.get('profile_completeness_score', 0) or 0),

        # --- Skills ---
        'skill_names'       : skill_names,
        'skill_durations'   : get_skill_durations(skills),  # {skill: months}

        # --- Text blobs ---
        'all_desc'          : all_desc,           # top 2 roles, 400 chars each
        'headline'          : profile.get('headline', '') or '',
        'summary'           : (profile.get('summary', '') or '')[:500],
        'title'             : profile.get('current_title', '') or '',
        'company'           : profile.get('current_company', '') or '',

        # --- Location ---
        'location'          : profile.get('location', '') or '',
        'location_tier'     : get_location_tier(profile.get('location', '')),
        'willing_relocate'  : bool(signals.get('willing_to_relocate', False)),

        # --- Disqualifier flags ---
        'is_consulting_only': is_consulting_only,

        # --- Verification ---
        'verified_email'    : bool(signals.get('verified_email', False)),
        'verified_phone'    : bool(signals.get('verified_phone', False)),
        'linkedin_connected': bool(signals.get('linkedin_connected', False)),
    }

# Save
with open(f'{PRECOMPUTED}/feature_cache.json', 'w') as f:
    json.dump(feature_cache, f)

print(f'Saved feature_cache.json — {len(feature_cache)} candidates')
import pickle
from rank_bm25 import BM25Okapi

def build_candidate_text(cid):
    f = feature_cache[cid]
    text = f['headline'] + ' ' + f['summary'] + ' ' + \
           ' '.join(f['skill_names']) + ' ' + f['all_desc']
    return text.lower().split()

all_cids    = list(feature_cache.keys())
corpus      = [build_candidate_text(cid) for cid in all_cids]
bm25_index  = BM25Okapi(corpus)

# Save index and the cid order it maps to
with open(f'{PRECOMPUTED}/bm25_index.pkl', 'wb') as f:
    pickle.dump({'index': bm25_index, 'cids': all_cids}, f)

print(f'Saved bm25_index.pkl — {len(all_cids)} candidates indexed')
import numpy as np
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('BAAI/bge-small-en-v1.5')

def build_embed_text(cid):
    f = feature_cache[cid]
    return f['headline'] + ' ' + f['summary'] + ' ' + ' '.join(f['skill_names'])

all_cids = list(feature_cache.keys())
texts    = [build_embed_text(cid) for cid in all_cids]

print(f'Encoding {len(texts)} candidates...')
embeddings = model.encode(
    texts,
    batch_size     = 64,
    show_progress_bar = True,
    normalize_embeddings = True,   # important — makes cosine = dot product
    convert_to_numpy = True
)

np.save(f'{PRECOMPUTED}/embeddings.npy',   embeddings.astype('float32'))
np.save(f'{PRECOMPUTED}/embed_cids.npy',   np.array(all_cids))    # cid order

print(f'Saved embeddings.npy — shape {embeddings.shape}')
import numpy as np
from sentence_transformers import SentenceTransformer

# Reuse model if still in memory from Cell 7, else reload
try:
    model
    print('Reusing model from Cell 7')
except NameError:
    model = SentenceTransformer('BAAI/bge-small-en-v1.5')
    print('Reloaded model')

# Build candidates dict for quick lookup
candidates_dict = {c['candidate_id']: c for c in candidates}

def build_rich_embed_text(cid):
    f    = feature_cache[cid]
    cand = candidates_dict[cid]

    career = sorted(
        cand.get('career_history', []),
        key=lambda x: x.get('duration_months', 0),
        reverse=True
    )[:2]

    career_text = ' '.join([
        f"{j.get('title', '')} at {j.get('company', '')} "
        f"{j.get('description', '')[:300]}"
        for j in career
    ])

    return (
        f['headline'] + ' ' +
        f['summary'] + ' ' +
        ' '.join(f['skill_names']) + ' ' +
        career_text
    ).strip()

# --- Rich embeddings ---
all_cids   = list(feature_cache.keys())
rich_texts = [build_rich_embed_text(cid) for cid in all_cids]

print(f'Encoding {len(rich_texts)} candidates with rich text...')
rich_embeddings = model.encode(
    rich_texts,
    batch_size           = 64,
    show_progress_bar    = True,
    normalize_embeddings = True,
    convert_to_numpy     = True
)

np.save(f'{PRECOMPUTED}/embeddings_rich.npy', rich_embeddings.astype('float32'))
np.save(f'{PRECOMPUTED}/embed_cids_rich.npy', np.array(all_cids))
print(f'Saved embeddings_rich.npy — shape {rich_embeddings.shape}')

# --- Combined JD vector ---
JD_TEXT_ORIGINAL = """
Senior AI Engineer founding team Redrob AI Series A Pune Noida India hybrid.
5 to 9 years experience. Production embeddings retrieval systems sentence-transformers
BGE E5 OpenAI embeddings embedding drift index refresh retrieval quality regression.
Vector databases hybrid search Pinecone Weaviate Qdrant Milvus OpenSearch Elasticsearch
FAISS operational experience. Strong Python code quality. Evaluation frameworks ranking
systems NDCG MRR MAP offline to online correlation A/B test interpretation.
LLM fine-tuning LoRA QLoRA PEFT learning to rank XGBoost neural HR tech recruiting
marketplace recommendation systems distributed systems inference optimization.
Product company experience not pure research not consulting only.
Shipper mindset owns intelligence layer ranking retrieval matching systems.
"""

JD_TEXT_SUMMARY = """
Senior AI Engineer at Redrob AI. Must have: production embeddings-based retrieval,
vector databases Pinecone Weaviate Qdrant FAISS OpenSearch, Python, evaluation
frameworks NDCG MRR A/B testing. Nice to have: LLM fine-tuning LoRA QLoRA,
learning to rank, recommendation systems. Product company experience. India location.
5-9 years experience. Shipper mindset not pure researcher.
"""

jd_vec_orig    = model.encode(
    [JD_TEXT_ORIGINAL],
    normalize_embeddings = True,
    convert_to_numpy     = True
)[0].astype('float32')

jd_vec_summary = model.encode(
    [JD_TEXT_SUMMARY],
    normalize_embeddings = True,
    convert_to_numpy     = True
)[0].astype('float32')

jd_vec_combined = jd_vec_orig + jd_vec_summary
jd_vec_combined = jd_vec_combined / np.linalg.norm(jd_vec_combined)

np.save(f'{PRECOMPUTED}/jd_vector_combined.npy', jd_vec_combined.astype('float32'))
print(f'Saved jd_vector_combined.npy — shape {jd_vec_combined.shape}')
import numpy as np
from sentence_transformers import SentenceTransformer
import re

# Reuse model if still in memory
try:
    model
    print('Reusing model from Cell 7')
except NameError:
    model = SentenceTransformer('BAAI/bge-small-en-v1.5')
    print('Reloaded model')

# ── Tier keyword lists (same as rank.ipynb) ──────────────────────────────

TIER1_DESC_KEYWORDS = [
    'embedding', 'embeddings', 'sbert', 'sentence-transformer',
    'sentence transformer', 'bge', 'e5', 'faiss', 'pinecone',
    'weaviate', 'qdrant', 'milvus', 'opensearch', 'elasticsearch',
    'vector', 'dense retrieval', 'hybrid search', 'semantic search',
    'ndcg', 'mrr', 'map', 'ranking', 're-rank', 'rerank',
    'retrieval', 'bm25', 'index refresh', 'embedding drift',
    'recommendation', 'recommender', 'learning to rank', 'ltr',
    'collaborative filtering', 'xgboost rank', 'two-tower',
    'colbert', 'dpr', 'dense passage'
]

TIER2_DESC_KEYWORDS = [
    'lora', 'qlora', 'peft', 'fine-tun', 'fine tuning',
    'nlp', 'text classification', 'ner', 'summarization',
    'inference optimization', 'feature store', 'mlflow',
    'distributed training', 'large language model', 'llm',
    'transformer', 'bert', 'gpt', 'hr tech', 'recruiting'
]

TIER3_DESC_KEYWORDS = [
    'spark', 'airflow', 'kafka', 'dbt', 'snowflake',
    'backend', 'api', 'microservice', 'computer vision',
    'speech', 'robotics', 'mlops', 'devops', 'cloud',
    'analytics', 'data engineering', 'data pipeline'
]

TIER_MULTIPLIERS = {1: 1.0, 2: 0.80, 3: 0.30, 4: 0.0}

def detect_desc_tier(text):
    """Keyword-based tier detection for career description."""
    t = text.lower()
    if any(kw in t for kw in TIER1_DESC_KEYWORDS):
        return 1
    if any(kw in t for kw in TIER2_DESC_KEYWORDS):
        return 2
    if any(kw in t for kw in TIER3_DESC_KEYWORDS):
        return 3
    return 4

def get_best_description(career):
    """
    Pick single best description from career history.
    Best = highest tier → tie break by raw text length (more detail = better).
    Returns (description_text, tier_multiplier)
    """
    if not career:
        return '', 0.0

    best_desc = ''
    best_tier = 5  # lower is better
    best_len  = 0

    for role in career:
        desc = role.get('description', '') or ''
        if not desc.strip():
            continue
        tier = detect_desc_tier(desc)
        length = len(desc)

        if tier < best_tier or (tier == best_tier and length > best_len):
            best_tier = tier
            best_desc = desc
            best_len  = length

    tier_mult = TIER_MULTIPLIERS.get(best_tier, 0.0)
    return best_desc.strip(), tier_mult

def chunk_text(text, chunk_size=3):
    """
    Split text into chunks of ~chunk_size sentences.
    Returns list of chunk strings.
    """
    if not text:
        return ['']
    # Split on sentence boundaries
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    sentences = [s.strip() for s in sentences if s.strip()]

    if not sentences:
        return [text[:500]]

    chunks = []
    for i in range(0, len(sentences), chunk_size):
        chunk = ' '.join(sentences[i:i + chunk_size])
        if chunk:
            chunks.append(chunk)

    return chunks if chunks else [text[:500]]

# ── Build chunk embeddings ────────────────────────────────────────────────

CHUNK_SIZE      = 3    # sentences per chunk
CHUNK_EMB_PATH  = f'{PRECOMPUTED}/chunk_embeddings.npy'

print(f'Building chunk embeddings for {len(candidates)} candidates...')

all_chunks_flat  = []
chunk_boundaries = [0]
cids_order       = []

for cand in candidates:
    cid    = cand['candidate_id']
    career = cand.get('career_history', [])

    best_desc, tier_mult = get_best_description(career)
    chunks = chunk_text(best_desc, CHUNK_SIZE)

    all_chunks_flat.extend(chunks)
    chunk_boundaries.append(len(all_chunks_flat))
    cids_order.append(cid)

print(f'  Total chunks to encode: {len(all_chunks_flat)}')
print(f'  Avg chunks per candidate: {len(all_chunks_flat) / len(candidates):.1f}')

# Encode all chunks in one pass
print('  Encoding chunks...')
chunk_vecs = model.encode(
    all_chunks_flat,
    batch_size           = 256,
    normalize_embeddings = True,
    show_progress_bar    = True,
    convert_to_numpy     = True
)

# Build dict {cid: chunk_embedding_matrix}
print('  Building chunk embedding dict...')
chunk_emb_dict = {}
for i, cid in enumerate(cids_order):
    start = chunk_boundaries[i]
    end   = chunk_boundaries[i + 1]
    chunk_emb_dict[cid] = chunk_vecs[start:end].astype('float32')

# Save
np.save(CHUNK_EMB_PATH, chunk_emb_dict)
print(f'  Saved chunk_embeddings.npy')
print(f'  Dict size: {len(chunk_emb_dict)} candidates')
print(f'  Embedding dim: {chunk_vecs.shape[1]}')
print(f'  Estimated file size: ~{chunk_vecs.nbytes / 1e6:.0f} MB')
import numpy as np

chunk_emb_data = np.load(f'{PRECOMPUTED}/chunk_embeddings.npy', allow_pickle=True).item()

print(f'Candidates in chunk_emb_data : {len(chunk_emb_data)}')

# Sample one candidate
sample_cid  = list(chunk_emb_data.keys())[0]
sample_embs = chunk_emb_data[sample_cid]

print(f'Sample CID                   : {sample_cid}')
print(f'Chunk count                  : {sample_embs.shape[0]}')
print(f'Embedding dim                : {sample_embs.shape[1]}')
print(f'Expected dim (bge-small)     : 384')

if len(chunk_emb_data) == 100000:
    print('\n✓ All 100k candidates have chunk embeddings')
elif len(chunk_emb_data) > 90000:
    print(f'\n⚠ {100000 - len(chunk_emb_data)} candidates missing')
else:
    print(f'\n✗ Only {len(chunk_emb_data)} candidates — re-run Cell 7C')
JD_TEXT = """
Senior AI Engineer at Redrob AI. Must have: production embeddings-based retrieval,
vector databases (Pinecone, Weaviate, Qdrant, FAISS, OpenSearch), Python, evaluation
frameworks (NDCG, MRR, A/B testing). Nice to have: LLM fine-tuning (LoRA, QLoRA),
learning to rank, recommendation systems. Product company experience. India location.
5-9 years experience. Shipper mindset, not pure researcher.
"""

jd_vec = model.encode(
    [JD_TEXT],
    normalize_embeddings = True,
    convert_to_numpy     = True
)[0].astype('float32')

np.save(f'{PRECOMPUTED}/jd_vector.npy', jd_vec)
print(f'Saved jd_vector.npy — shape {jd_vec.shape}')

import os

PRECOMPUTED = os.environ.get('PRECOMPUTED_DIR', './precomputed')
TOP200_CSV  = os.environ.get('TOP200_CSV_PATH', f'{PRECOMPUTED}/merged_top200_with_details.csv')

# ============================================================
# PHASE A — BGE Reranker Inference + Score Caching
# 3 separate inference passes: description, headline, summary
# Headline gets tier + seniority multiplier on raw scores
# Blend raw scores directly, minmax only on final blended score
# Weights: desc=0.50, headline=0.30, summary=0.20
# Output: 4 JSON files in precomputed/
# ============================================================

import csv
import json
import os
import numpy as np
from sentence_transformers import CrossEncoder

print('\n' + '='*60)
print('PHASE A — BGE Reranker 3-Pass Inference + Caching')
print('='*60)

# ── JD Text ───────────────────────────────────────────────────────────────
JD_TEXT = """Senior AI Engineer — Founding Team, Redrob AI (Series A, Pune/Noida).

Own the intelligence layer: ranking, retrieval, and candidate-JD matching systems that decide what recruiters see when they search. Ship v2 ranker improving recruiter engagement metrics. Build evaluation infrastructure — offline benchmarks, NDCG, MRR, MAP, online A/B testing, recruiter feedback loops, offline-to-online correlation.

Must have — production experience with: embeddings-based retrieval deployed to real users (sentence-transformers, BGE, E5, OpenAI embeddings); embedding drift, index refresh, retrieval-quality regression in production; vector databases or hybrid search (Pinecone, Weaviate, Qdrant, Milvus, FAISS, OpenSearch, Elasticsearch); strong Python and code quality; evaluation frameworks for ranking systems (NDCG, MRR, MAP, A/B test interpretation).

Nice to have: LLM fine-tuning (LoRA, QLoRA, PEFT), learning-to-rank (XGBoost, LambdaMART, LTR), HR-tech or marketplace products, distributed systems, large-scale inference, open-source contributions in AI/ML.

Explicit disqualifiers: pure research roles without production deployment; LangChain-only AI experience under 12 months; architect/tech-lead roles not writing production code in last 18 months; consulting-only career (TCS, Infosys, Wipro, Accenture); computer vision, speech, robotics without NLP/IR exposure.

Ideal profile: 6-8 years total, 4-5 in applied ML at product companies (not services). Shipped at least one end-to-end ranking, search, or recommendation system to real users at meaningful scale. Strong opinions on hybrid vs dense retrieval, offline vs online evaluation, when to fine-tune vs prompt — backed by systems actually built. Sub-30-day notice preferred."""

print(f'JD token count: {len(JD_TEXT.split())}')

# ── Headline tier + seniority multipliers ─────────────────────────────────
HEADLINE_TIER = {
    1: {
        'mult': 1.20,
        'terms': [
            'search engineer', 'ranking engineer', 'retrieval engineer',
            'recommendation systems engineer', 'nlp engineer',
            'applied scientist', 'applied ml engineer',
            'ml engineer', 'ai engineer', 'machine learning engineer',
            'information retrieval', 'search & ranking', 'search and ranking',
            'recommendation systems', 'nlp', 'search & discovery',
        ]
    },
    2: {
        'mult': 1.10,
        'terms': [
            'data scientist', 'senior software engineer (ml)',
            'software engineer (ml)', 'ai specialist',
            'deep learning engineer', 'mlops engineer', 'llm engineer',
            'llm', 'large language model',
        ]
    },
    3: {
        'mult': 1.00,
        'terms': [
            'software engineer', 'data engineer', 'backend',
            'full stack', 'platform engineer',
        ]
    },
    4: {
        'mult': 0.80,
        'terms': [
            'ai research engineer', 'research engineer', 'research scientist',
            'computer vision engineer', 'computer vision',
            'hr manager', 'operations manager', 'project manager',
            'data analyst', 'generative ai explorer', 'ai enthusiast',
            'data pipelines', 'analytics',
        ]
    },
}

SENIORITY_MULT = {
    'boost_high': {'terms': ['lead', 'staff', 'principal', 'head'], 'mult': 1.10},
    'boost_low':  {'terms': ['senior', 'sr.'],                      'mult': 1.05},
    'penalty':    {'terms': ['junior', 'jr.', 'intern'],            'mult': 0.85},
}

def get_headline_multiplier(headline):
    h = (headline or '').lower()
    tier_mult = 1.00
    for tier in [1, 2, 3, 4]:
        if any(term in h for term in HEADLINE_TIER[tier]['terms']):
            tier_mult = HEADLINE_TIER[tier]['mult']
            break
    if any(t in h for t in SENIORITY_MULT['boost_high']['terms']):
        sen_mult = SENIORITY_MULT['boost_high']['mult']
    elif any(t in h for t in SENIORITY_MULT['boost_low']['terms']):
        sen_mult = SENIORITY_MULT['boost_low']['mult']
    elif any(t in h for t in SENIORITY_MULT['penalty']['terms']):
        sen_mult = SENIORITY_MULT['penalty']['mult']
    else:
        sen_mult = 1.00
    return tier_mult, sen_mult

# ── Helpers ────────────────────────────────────────────────────────────────
def truncate(text, max_tokens):
    return ' '.join((text or '').split()[:max_tokens])

def minmax_final(arr):
    mn, mx = arr.min(), arr.max()
    return (arr - mn) / (mx - mn + 1e-9)

# ── Load top 200 CSV ───────────────────────────────────────────────────────
print(f'\n[Phase A] Loading top 200 from: {TOP200_CSV}')
rows = []
with open(TOP200_CSV, encoding='utf-8-sig') as f:
    reader = csv.DictReader(f)
    for row in reader:
        rows.append(row)
print(f'  Loaded {len(rows)} candidates')

# ── Extract fields ─────────────────────────────────────────────────────────
ordered_cids   = []
desc_texts     = []
headline_texts = []
summary_texts  = []

for row in rows:
    cid = row['candidate_id']
    ordered_cids.append(cid)
    desc_texts.append(truncate(row.get('ranking_career_description', '') or '', max_tokens=400))
    headline_texts.append((row.get('profile_headline', '') or '').strip())
    summary_texts.append(truncate(row.get('profile_summary', '') or '', max_tokens=80))

print(f'  Fields extracted : {len(ordered_cids)} candidates')
print(f'  Sample desc      : {desc_texts[0][:100]}...')
print(f'  Sample headline  : {headline_texts[0]}')
print(f'  Sample summary   : {summary_texts[0][:100]}...')

# ── Load BGE Reranker ──────────────────────────────────────────────────────
print('\n[Phase A] Loading BAAI/bge-reranker-v2-m3...')
reranker = CrossEncoder(
    'BAAI/bge-reranker-v2-m3',
    max_length=512,
    automodel_args={'torch_dtype': 'auto'},
)
print('  Model loaded.')

# ── Pass 1 — Career Description ────────────────────────────────────────────
print('\n[Phase A] Pass 1/3 — Career Description...')
desc_pairs = [[JD_TEXT, t] for t in desc_texts]
raw_desc   = reranker.predict(desc_pairs, batch_size=8, show_progress_bar=True)
print(f'  Raw range: {raw_desc.min():.4f} to {raw_desc.max():.4f}')

# ── Pass 2 — Headline ──────────────────────────────────────────────────────
print('\n[Phase A] Pass 2/3 — Headline...')
headline_pairs = [[JD_TEXT, t] for t in headline_texts]
raw_headline   = reranker.predict(headline_pairs, batch_size=8, show_progress_bar=True)
print(f'  Raw range: {raw_headline.min():.4f} to {raw_headline.max():.4f}')

# Apply tier + seniority multipliers directly on raw headline scores
headline_boosted = []
for i, cid in enumerate(ordered_cids):
    tier_mult, sen_mult = get_headline_multiplier(headline_texts[i])
    headline_boosted.append(float(raw_headline[i]) * tier_mult * sen_mult)
headline_boosted = np.array(headline_boosted)
print(f'  Boosted range: {headline_boosted.min():.4f} to {headline_boosted.max():.4f}')

# ── Pass 3 — Summary ──────────────────────────────────────────────────────
print('\n[Phase A] Pass 3/3 — Summary...')
summary_pairs = [[JD_TEXT, t if t.strip() else 'no summary provided'] for t in summary_texts]
raw_summary   = reranker.predict(summary_pairs, batch_size=8, show_progress_bar=True)
print(f'  Raw range: {raw_summary.min():.4f} to {raw_summary.max():.4f}')

# ── Minmax on career description only before blending ─────────────────────
mm_desc = minmax_final(raw_desc)
print(f'  desc minmax range: {mm_desc.min():.4f} to {mm_desc.max():.4f}')

# ── Blend: minmaxed desc + raw headline boosted + raw summary ─────────────
print('\n[Phase A] Blending scores (desc=0.50, headline=0.30, summary=0.20)...')
W_DESC, W_HEAD, W_SUM = 0.50, 0.30, 0.20
blended = W_DESC * mm_desc + W_HEAD * headline_boosted + W_SUM * raw_summary
print(f'  Blended range: {blended.min():.4f} to {blended.max():.4f}')

# ── Minmax on final blended score only ────────────────────────────────────
normalized_cross = minmax_final(blended)
print(f'  Normalized range: {normalized_cross.min():.4f} to {normalized_cross.max():.4f}')

# ── Distribution stats ─────────────────────────────────────────────────────
all_scores = sorted(normalized_cross.tolist(), reverse=True)
print(f'\n  Top 10 avg  : {np.mean(all_scores[:10]):.4f}')
print(f'  Top 50 avg  : {np.mean(all_scores[:50]):.4f}')
print(f'  Bottom 50   : {np.mean(all_scores[150:]):.4f}')
print(f'  Std dev     : {np.std(all_scores):.4f}')

# ── Save cache files ───────────────────────────────────────────────────────
os.makedirs(PRECOMPUTED, exist_ok=True)

cache_desc = {
    cid: {'raw': float(raw_desc[i])}
    for i, cid in enumerate(ordered_cids)
}
cache_headline = {
    cid: {
        'raw':     float(raw_headline[i]),
        'boosted': float(headline_boosted[i]),
    }
    for i, cid in enumerate(ordered_cids)
}
cache_summary = {
    cid: {'raw': float(raw_summary[i])}
    for i, cid in enumerate(ordered_cids)
}
cache_blended = {
    cid: {
        'blended':    float(blended[i]),
        'normalized': float(normalized_cross[i]),
    }
    for i, cid in enumerate(ordered_cids)
}

paths = {
    'cross_scores_desc_top200.json':     cache_desc,
    'cross_scores_headline_top200.json': cache_headline,
    'cross_scores_summary_top200.json':  cache_summary,
    'cross_scores_blended_top200.json':  cache_blended,
}
for fname, cache in paths.items():
    path = f'{PRECOMPUTED}/{fname}'
    with open(path, 'w') as f:
        json.dump(cache, f, indent=2)
    print(f'  Saved: {path}')

# ── Sanity check — top 10 ─────────────────────────────────────────────────
sorted_cids = sorted(enumerate(ordered_cids), key=lambda x: -normalized_cross[x[0]])
print('\n  Top 10 by normalized cross score:')
print(f'  {"Rank":<5} {"candidate_id":<18} {"norm_cross":<12} {"desc_raw":<10} {"head_boost":<12} {"sum_raw"}')
print('  ' + '-'*72)
for rank, (i, cid) in enumerate(sorted_cids[:10], 1):
    print(f'  {rank:<5} {cid:<18} {normalized_cross[i]:<12.4f} '
          f'{raw_desc[i]:<10.4f} {headline_boosted[i]:<12.4f} {raw_summary[i]:.4f}')

print('\n[Phase A] Done. 4 cache files written to precomputed/.')
print('Proceed to Phase B to update rank.py.')